services:
  - type: web
    name: gomoku-multi
    env: node
    buildCommand: npm install && mkdir -p dist && npx tsc server/index.ts --outDir dist --module commonjs --target es2020 --esModuleInterop --skipLibCheck && npx vite build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
